version: "3"
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "athun123"
      POSTGRES_DB: "booknow"
    ports:
      - "5433:5432"
    networks:
      - servicenetwork
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    image: auth-svc:latest
    container_name: auth-svc-container
    ports:
      - "7777:7777"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "athun123"
      POSTGRES_DB: "booknow"
      POSTGRES_HOST: "db"
    networks:
      - servicenetwork

  api:
    build: .
    image: apigateway:latest
    container_name: apigate-container
    ports:
      - "8000:8000"
    restart: always
    networks:
      - servicenetwork

volumes:
  dbdata:

networks:
  servicenetwork:
    driver: bridge
