// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/athunlal/bookNow-auth-svc/pkg/api"
	"github.com/athunlal/bookNow-auth-svc/pkg/api/handler"
	"github.com/athunlal/bookNow-auth-svc/pkg/config"
	"github.com/athunlal/bookNow-auth-svc/pkg/db"
	"github.com/athunlal/bookNow-auth-svc/pkg/repository"
	"github.com/athunlal/bookNow-auth-svc/pkg/usecase"
)

// Injectors from wire.go:

func InitApi(cfg config.Config) (*api.ServerHttp, error) {
	gormDB, err := db.ConnectToDb(cfg)
	if err != nil {
		return nil, err
	}
	userRepo := repository.NewUserRepo(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepo)
	jwtUseCase := usecase.NewJWTUseCase()
	userHandler := handler.NewUserHandler(userUseCase, jwtUseCase)
	serverHttp := api.NewServerHttp(userHandler)
	return serverHttp, nil
}
